//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jojo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangxoahoadon
    {
        public int id { get; set; }
        public int idhoadon { get; set; }
        public int idnhanvien { get; set; }
        public System.DateTime ngay { get; set; }
        public string active { get; set; }
    
        public virtual hoadon hoadon { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
