//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jojo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public khachhang()
        {
            this.hoadons = new HashSet<hoadon>();
        }
    
        public int id { get; set; }
        public string tenkhachhang { get; set; }
        public string sodienthoai { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string ghichu { get; set; }
        public string trangthai { get; set; }
        public string active { get; set; }
    
        public virtual ICollection<hoadon> hoadons { get; set; }
    }
}
