//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jojo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaichiphi
    {
        public loaichiphi()
        {
            this.chiphis = new HashSet<chiphi>();
        }
    
        public int id { get; set; }
        public string tenchiphi { get; set; }
    
        public virtual ICollection<chiphi> chiphis { get; set; }
    }
}
