//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jojo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public nhanvien()
        {
            this.bangxoahoadons = new HashSet<bangxoahoadon>();
            this.hoadons = new HashSet<hoadon>();
        }
    
        public int id { get; set; }
        public string matkhau { get; set; }
        public string hovaten { get; set; }
        public string gioitinh { get; set; }
        public string ngaysinh { get; set; }
        public string sodienthoai { get; set; }
        public string diachi { get; set; }
        public string cmnd { get; set; }
        public string ngayvaolam { get; set; }
        public string congviec { get; set; }
        public string taikhoan { get; set; }
        public int loai { get; set; }
        public string active { get; set; }
    
        public virtual ICollection<bangxoahoadon> bangxoahoadons { get; set; }
        public virtual ICollection<hoadon> hoadons { get; set; }
    }
}
