//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jojo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public sanpham()
        {
            this.chitiethoadons = new HashSet<chitiethoadon>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public int gia { get; set; }
        public string loai { get; set; }
        public string active { get; set; }
    
        public virtual ICollection<chitiethoadon> chitiethoadons { get; set; }
    }
}
